/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessibilidadeRouteImport } from './routes/acessibilidade'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as ApoieRouteImport } from './routes/apoie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BussolaVozRouteImport } from './routes/bussola-voz'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MeusProdutosRouteImport } from './routes/meus-produtos'
import { Route as OMovimentoRouteImport } from './routes/o-movimento'
import { Route as ParticipeRouteImport } from './routes/participe'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as SejaVozRouteImport } from './routes/seja-voz'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PagamentoAprovadoRouteImport } from './routes/pagamento.aprovado'
import { Route as PagamentoPendenteRouteImport } from './routes/pagamento.pendente'
import { Route as PagamentoProcessandoRouteImport } from './routes/pagamento.processando'
import { Route as PagamentoRecusadoRouteImport } from './routes/pagamento.recusado'
import { Route as SolucoesVozProtetoraRouteImport } from './routes/solucoes_.voz-protetora'
import { Route as VozProtetoraIndexRouteImport } from './routes/voz-protetora.index'
import { Route as VozProtetoraSplatRouteImport } from './routes/voz-protetora.$'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicKeepaliveRouteImport } from './routes/api/public/keepalive'
import { Route as AuthenticatedAppVozProtetoraIndexRouteImport } from './routes/_authenticated/app.voz-protetora.index'
import { Route as AuthenticatedAppVozProtetoraBuscaRouteImport } from './routes/_authenticated/app.voz-protetora.busca'
import { Route as AuthenticatedAppVozProtetoraComoUsarRouteImport } from './routes/_authenticated/app.voz-protetora.como-usar'
import { Route as AuthenticatedAppVozProtetoraMeuPassoRouteImport } from './routes/_authenticated/app.voz-protetora.meu-passo'
import { Route as AuthenticatedAppVozProtetoraMinhaAssinaturaRouteImport } from './routes/_authenticated/app.voz-protetora.minha-assinatura'
import { Route as AuthenticatedAppVozProtetoraMinhaPresencaRouteImport } from './routes/_authenticated/app.voz-protetora.minha-presenca'
import { Route as AuthenticatedAppVozProtetoraMinhaVozRouteImport } from './routes/_authenticated/app.voz-protetora.minha-voz'
import { Route as AuthenticatedAppVozProtetoraNotificacoesRouteImport } from './routes/_authenticated/app.voz-protetora.notificacoes'
import { Route as AuthenticatedAppVozProtetoraPrecisoDeAjudaRouteImport } from './routes/_authenticated/app.voz-protetora.preciso-de-ajuda'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as AuthenticatedAppVozProtetoraAconteceuIndexRouteImport } from './routes/_authenticated/app.voz-protetora.aconteceu.index'
import { Route as AuthenticatedAppVozProtetoraAconteceuSlugRouteImport } from './routes/_authenticated/app.voz-protetora.aconteceu.$slug'
import { Route as AuthenticatedAppVozProtetoraBonusIndexRouteImport } from './routes/_authenticated/app.voz-protetora.bonus.index'
import { Route as AuthenticatedAppVozProtetoraBonusSlugRouteImport } from './routes/_authenticated/app.voz-protetora.bonus.$slug'
import { Route as AuthenticatedAppVozProtetoraFortalecerIndexRouteImport } from './routes/_authenticated/app.voz-protetora.fortalecer.index'
import { Route as AuthenticatedAppVozProtetoraFortalecerSlugRouteImport } from './routes/_authenticated/app.voz-protetora.fortalecer.$slug'
import { Route as AuthenticatedAppVozProtetoraVaiAcontecerIndexRouteImport } from './routes/_authenticated/app.voz-protetora.vai-acontecer.index'
import { Route as AuthenticatedAppVozProtetoraVaiAcontecerSlugRouteImport } from './routes/_authenticated/app.voz-protetora.vai-acontecer.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessibilidadeRoute = AcessibilidadeRouteImport.update({
  id: '/acessibilidade',
  path: '/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoieRoute = ApoieRouteImport.update({
  id: '/apoie',
  path: '/apoie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BussolaVozRoute = BussolaVozRouteImport.update({
  id: '/bussola-voz',
  path: '/bussola-voz',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProdutosRoute = MeusProdutosRouteImport.update({
  id: '/meus-produtos',
  path: '/meus-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OMovimentoRoute = OMovimentoRouteImport.update({
  id: '/o-movimento',
  path: '/o-movimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipeRoute = ParticipeRouteImport.update({
  id: '/participe',
  path: '/participe',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaVozRoute = SejaVozRouteImport.update({
  id: '/seja-voz',
  path: '/seja-voz',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PagamentoAprovadoRoute = PagamentoAprovadoRouteImport.update({
  id: '/pagamento/aprovado',
  path: '/pagamento/aprovado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPendenteRoute = PagamentoPendenteRouteImport.update({
  id: '/pagamento/pendente',
  path: '/pagamento/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoProcessandoRoute = PagamentoProcessandoRouteImport.update({
  id: '/pagamento/processando',
  path: '/pagamento/processando',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRecusadoRoute = PagamentoRecusadoRouteImport.update({
  id: '/pagamento/recusado',
  path: '/pagamento/recusado',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesVozProtetoraRoute = SolucoesVozProtetoraRouteImport.update({
  id: '/solucoes_/voz-protetora',
  path: '/solucoes/voz-protetora',
  getParentRoute: () => rootRouteImport,
} as any)
const VozProtetoraIndexRoute = VozProtetoraIndexRouteImport.update({
  id: '/voz-protetora/',
  path: '/voz-protetora/',
  getParentRoute: () => rootRouteImport,
} as any)
const VozProtetoraSplatRoute = VozProtetoraSplatRouteImport.update({
  id: '/voz-protetora/$',
  path: '/voz-protetora/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicKeepaliveRoute = ApiPublicKeepaliveRouteImport.update({
  id: '/api/public/keepalive',
  path: '/api/public/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVozProtetoraIndexRoute =
  AuthenticatedAppVozProtetoraIndexRouteImport.update({
    id: '/app/voz-protetora/',
    path: '/app/voz-protetora/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraBuscaRoute =
  AuthenticatedAppVozProtetoraBuscaRouteImport.update({
    id: '/app/voz-protetora/busca',
    path: '/app/voz-protetora/busca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraComoUsarRoute =
  AuthenticatedAppVozProtetoraComoUsarRouteImport.update({
    id: '/app/voz-protetora/como-usar',
    path: '/app/voz-protetora/como-usar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraMeuPassoRoute =
  AuthenticatedAppVozProtetoraMeuPassoRouteImport.update({
    id: '/app/voz-protetora/meu-passo',
    path: '/app/voz-protetora/meu-passo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraMinhaAssinaturaRoute =
  AuthenticatedAppVozProtetoraMinhaAssinaturaRouteImport.update({
    id: '/app/voz-protetora/minha-assinatura',
    path: '/app/voz-protetora/minha-assinatura',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraMinhaPresencaRoute =
  AuthenticatedAppVozProtetoraMinhaPresencaRouteImport.update({
    id: '/app/voz-protetora/minha-presenca',
    path: '/app/voz-protetora/minha-presenca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraMinhaVozRoute =
  AuthenticatedAppVozProtetoraMinhaVozRouteImport.update({
    id: '/app/voz-protetora/minha-voz',
    path: '/app/voz-protetora/minha-voz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraNotificacoesRoute =
  AuthenticatedAppVozProtetoraNotificacoesRouteImport.update({
    id: '/app/voz-protetora/notificacoes',
    path: '/app/voz-protetora/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute =
  AuthenticatedAppVozProtetoraPrecisoDeAjudaRouteImport.update({
    id: '/app/voz-protetora/preciso-de-ajuda',
    path: '/app/voz-protetora/preciso-de-ajuda',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppVozProtetoraAconteceuIndexRoute =
  AuthenticatedAppVozProtetoraAconteceuIndexRouteImport.update({
    id: '/app/voz-protetora/aconteceu/',
    path: '/app/voz-protetora/aconteceu/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraAconteceuSlugRoute =
  AuthenticatedAppVozProtetoraAconteceuSlugRouteImport.update({
    id: '/app/voz-protetora/aconteceu/$slug',
    path: '/app/voz-protetora/aconteceu/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraBonusIndexRoute =
  AuthenticatedAppVozProtetoraBonusIndexRouteImport.update({
    id: '/app/voz-protetora/bonus/',
    path: '/app/voz-protetora/bonus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraBonusSlugRoute =
  AuthenticatedAppVozProtetoraBonusSlugRouteImport.update({
    id: '/app/voz-protetora/bonus/$slug',
    path: '/app/voz-protetora/bonus/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraFortalecerIndexRoute =
  AuthenticatedAppVozProtetoraFortalecerIndexRouteImport.update({
    id: '/app/voz-protetora/fortalecer/',
    path: '/app/voz-protetora/fortalecer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraFortalecerSlugRoute =
  AuthenticatedAppVozProtetoraFortalecerSlugRouteImport.update({
    id: '/app/voz-protetora/fortalecer/$slug',
    path: '/app/voz-protetora/fortalecer/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute =
  AuthenticatedAppVozProtetoraVaiAcontecerIndexRouteImport.update({
    id: '/app/voz-protetora/vai-acontecer/',
    path: '/app/voz-protetora/vai-acontecer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute =
  AuthenticatedAppVozProtetoraVaiAcontecerSlugRouteImport.update({
    id: '/app/voz-protetora/vai-acontecer/$slug',
    path: '/app/voz-protetora/vai-acontecer/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/acesso': typeof AcessoRoute
  '/apoie': typeof ApoieRoute
  '/auth': typeof AuthRoute
  '/bussola-voz': typeof BussolaVozRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/metodologia': typeof MetodologiaRoute
  '/meus-produtos': typeof MeusProdutosRoute
  '/o-movimento': typeof OMovimentoRoute
  '/participe': typeof ParticipeRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/seja-voz': typeof SejaVozRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/pagamento/aprovado': typeof PagamentoAprovadoRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/processando': typeof PagamentoProcessandoRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/solucoes/voz-protetora': typeof SolucoesVozProtetoraRoute
  '/voz-protetora/$': typeof VozProtetoraSplatRoute
  '/voz-protetora/': typeof VozProtetoraIndexRoute
  '/api/public/keepalive': typeof ApiPublicKeepaliveRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/voz-protetora/busca': typeof AuthenticatedAppVozProtetoraBuscaRoute
  '/app/voz-protetora/como-usar': typeof AuthenticatedAppVozProtetoraComoUsarRoute
  '/app/voz-protetora/meu-passo': typeof AuthenticatedAppVozProtetoraMeuPassoRoute
  '/app/voz-protetora/minha-assinatura': typeof AuthenticatedAppVozProtetoraMinhaAssinaturaRoute
  '/app/voz-protetora/minha-presenca': typeof AuthenticatedAppVozProtetoraMinhaPresencaRoute
  '/app/voz-protetora/minha-voz': typeof AuthenticatedAppVozProtetoraMinhaVozRoute
  '/app/voz-protetora/notificacoes': typeof AuthenticatedAppVozProtetoraNotificacoesRoute
  '/app/voz-protetora/preciso-de-ajuda': typeof AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/voz-protetora/': typeof AuthenticatedAppVozProtetoraIndexRoute
  '/app/voz-protetora/aconteceu/$slug': typeof AuthenticatedAppVozProtetoraAconteceuSlugRoute
  '/app/voz-protetora/bonus/$slug': typeof AuthenticatedAppVozProtetoraBonusSlugRoute
  '/app/voz-protetora/fortalecer/$slug': typeof AuthenticatedAppVozProtetoraFortalecerSlugRoute
  '/app/voz-protetora/vai-acontecer/$slug': typeof AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute
  '/app/voz-protetora/aconteceu/': typeof AuthenticatedAppVozProtetoraAconteceuIndexRoute
  '/app/voz-protetora/bonus/': typeof AuthenticatedAppVozProtetoraBonusIndexRoute
  '/app/voz-protetora/fortalecer/': typeof AuthenticatedAppVozProtetoraFortalecerIndexRoute
  '/app/voz-protetora/vai-acontecer/': typeof AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/acesso': typeof AcessoRoute
  '/apoie': typeof ApoieRoute
  '/auth': typeof AuthRoute
  '/bussola-voz': typeof BussolaVozRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/metodologia': typeof MetodologiaRoute
  '/meus-produtos': typeof MeusProdutosRoute
  '/o-movimento': typeof OMovimentoRoute
  '/participe': typeof ParticipeRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/seja-voz': typeof SejaVozRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/pagamento/aprovado': typeof PagamentoAprovadoRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/processando': typeof PagamentoProcessandoRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/solucoes/voz-protetora': typeof SolucoesVozProtetoraRoute
  '/voz-protetora/$': typeof VozProtetoraSplatRoute
  '/voz-protetora': typeof VozProtetoraIndexRoute
  '/api/public/keepalive': typeof ApiPublicKeepaliveRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/voz-protetora/busca': typeof AuthenticatedAppVozProtetoraBuscaRoute
  '/app/voz-protetora/como-usar': typeof AuthenticatedAppVozProtetoraComoUsarRoute
  '/app/voz-protetora/meu-passo': typeof AuthenticatedAppVozProtetoraMeuPassoRoute
  '/app/voz-protetora/minha-assinatura': typeof AuthenticatedAppVozProtetoraMinhaAssinaturaRoute
  '/app/voz-protetora/minha-presenca': typeof AuthenticatedAppVozProtetoraMinhaPresencaRoute
  '/app/voz-protetora/minha-voz': typeof AuthenticatedAppVozProtetoraMinhaVozRoute
  '/app/voz-protetora/notificacoes': typeof AuthenticatedAppVozProtetoraNotificacoesRoute
  '/app/voz-protetora/preciso-de-ajuda': typeof AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/voz-protetora': typeof AuthenticatedAppVozProtetoraIndexRoute
  '/app/voz-protetora/aconteceu/$slug': typeof AuthenticatedAppVozProtetoraAconteceuSlugRoute
  '/app/voz-protetora/bonus/$slug': typeof AuthenticatedAppVozProtetoraBonusSlugRoute
  '/app/voz-protetora/fortalecer/$slug': typeof AuthenticatedAppVozProtetoraFortalecerSlugRoute
  '/app/voz-protetora/vai-acontecer/$slug': typeof AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute
  '/app/voz-protetora/aconteceu': typeof AuthenticatedAppVozProtetoraAconteceuIndexRoute
  '/app/voz-protetora/bonus': typeof AuthenticatedAppVozProtetoraBonusIndexRoute
  '/app/voz-protetora/fortalecer': typeof AuthenticatedAppVozProtetoraFortalecerIndexRoute
  '/app/voz-protetora/vai-acontecer': typeof AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acessibilidade': typeof AcessibilidadeRoute
  '/acesso': typeof AcessoRoute
  '/apoie': typeof ApoieRoute
  '/auth': typeof AuthRoute
  '/bussola-voz': typeof BussolaVozRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/metodologia': typeof MetodologiaRoute
  '/meus-produtos': typeof MeusProdutosRoute
  '/o-movimento': typeof OMovimentoRoute
  '/participe': typeof ParticipeRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/seja-voz': typeof SejaVozRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/pagamento/aprovado': typeof PagamentoAprovadoRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/processando': typeof PagamentoProcessandoRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/solucoes_/voz-protetora': typeof SolucoesVozProtetoraRoute
  '/voz-protetora/$': typeof VozProtetoraSplatRoute
  '/voz-protetora/': typeof VozProtetoraIndexRoute
  '/api/public/keepalive': typeof ApiPublicKeepaliveRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/voz-protetora/busca': typeof AuthenticatedAppVozProtetoraBuscaRoute
  '/_authenticated/app/voz-protetora/como-usar': typeof AuthenticatedAppVozProtetoraComoUsarRoute
  '/_authenticated/app/voz-protetora/meu-passo': typeof AuthenticatedAppVozProtetoraMeuPassoRoute
  '/_authenticated/app/voz-protetora/minha-assinatura': typeof AuthenticatedAppVozProtetoraMinhaAssinaturaRoute
  '/_authenticated/app/voz-protetora/minha-presenca': typeof AuthenticatedAppVozProtetoraMinhaPresencaRoute
  '/_authenticated/app/voz-protetora/minha-voz': typeof AuthenticatedAppVozProtetoraMinhaVozRoute
  '/_authenticated/app/voz-protetora/notificacoes': typeof AuthenticatedAppVozProtetoraNotificacoesRoute
  '/_authenticated/app/voz-protetora/preciso-de-ajuda': typeof AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/_authenticated/app/voz-protetora/': typeof AuthenticatedAppVozProtetoraIndexRoute
  '/_authenticated/app/voz-protetora/aconteceu/$slug': typeof AuthenticatedAppVozProtetoraAconteceuSlugRoute
  '/_authenticated/app/voz-protetora/bonus/$slug': typeof AuthenticatedAppVozProtetoraBonusSlugRoute
  '/_authenticated/app/voz-protetora/fortalecer/$slug': typeof AuthenticatedAppVozProtetoraFortalecerSlugRoute
  '/_authenticated/app/voz-protetora/vai-acontecer/$slug': typeof AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute
  '/_authenticated/app/voz-protetora/aconteceu/': typeof AuthenticatedAppVozProtetoraAconteceuIndexRoute
  '/_authenticated/app/voz-protetora/bonus/': typeof AuthenticatedAppVozProtetoraBonusIndexRoute
  '/_authenticated/app/voz-protetora/fortalecer/': typeof AuthenticatedAppVozProtetoraFortalecerIndexRoute
  '/_authenticated/app/voz-protetora/vai-acontecer/': typeof AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessibilidade'
    | '/acesso'
    | '/apoie'
    | '/auth'
    | '/bussola-voz'
    | '/checkout'
    | '/contato'
    | '/conteudos'
    | '/metodologia'
    | '/meus-produtos'
    | '/o-movimento'
    | '/participe'
    | '/politica-de-privacidade'
    | '/recursos'
    | '/seja-voz'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos-de-uso'
    | '/admin'
    | '/pagamento/aprovado'
    | '/pagamento/pendente'
    | '/pagamento/processando'
    | '/pagamento/recusado'
    | '/solucoes/voz-protetora'
    | '/voz-protetora/$'
    | '/voz-protetora/'
    | '/api/public/keepalive'
    | '/app/'
    | '/app/voz-protetora/busca'
    | '/app/voz-protetora/como-usar'
    | '/app/voz-protetora/meu-passo'
    | '/app/voz-protetora/minha-assinatura'
    | '/app/voz-protetora/minha-presenca'
    | '/app/voz-protetora/minha-voz'
    | '/app/voz-protetora/notificacoes'
    | '/app/voz-protetora/preciso-de-ajuda'
    | '/api/public/webhooks/mercadopago'
    | '/app/voz-protetora/'
    | '/app/voz-protetora/aconteceu/$slug'
    | '/app/voz-protetora/bonus/$slug'
    | '/app/voz-protetora/fortalecer/$slug'
    | '/app/voz-protetora/vai-acontecer/$slug'
    | '/app/voz-protetora/aconteceu/'
    | '/app/voz-protetora/bonus/'
    | '/app/voz-protetora/fortalecer/'
    | '/app/voz-protetora/vai-acontecer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessibilidade'
    | '/acesso'
    | '/apoie'
    | '/auth'
    | '/bussola-voz'
    | '/checkout'
    | '/contato'
    | '/conteudos'
    | '/metodologia'
    | '/meus-produtos'
    | '/o-movimento'
    | '/participe'
    | '/politica-de-privacidade'
    | '/recursos'
    | '/seja-voz'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos-de-uso'
    | '/admin'
    | '/pagamento/aprovado'
    | '/pagamento/pendente'
    | '/pagamento/processando'
    | '/pagamento/recusado'
    | '/solucoes/voz-protetora'
    | '/voz-protetora/$'
    | '/voz-protetora'
    | '/api/public/keepalive'
    | '/app'
    | '/app/voz-protetora/busca'
    | '/app/voz-protetora/como-usar'
    | '/app/voz-protetora/meu-passo'
    | '/app/voz-protetora/minha-assinatura'
    | '/app/voz-protetora/minha-presenca'
    | '/app/voz-protetora/minha-voz'
    | '/app/voz-protetora/notificacoes'
    | '/app/voz-protetora/preciso-de-ajuda'
    | '/api/public/webhooks/mercadopago'
    | '/app/voz-protetora'
    | '/app/voz-protetora/aconteceu/$slug'
    | '/app/voz-protetora/bonus/$slug'
    | '/app/voz-protetora/fortalecer/$slug'
    | '/app/voz-protetora/vai-acontecer/$slug'
    | '/app/voz-protetora/aconteceu'
    | '/app/voz-protetora/bonus'
    | '/app/voz-protetora/fortalecer'
    | '/app/voz-protetora/vai-acontecer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acessibilidade'
    | '/acesso'
    | '/apoie'
    | '/auth'
    | '/bussola-voz'
    | '/checkout'
    | '/contato'
    | '/conteudos'
    | '/metodologia'
    | '/meus-produtos'
    | '/o-movimento'
    | '/participe'
    | '/politica-de-privacidade'
    | '/recursos'
    | '/seja-voz'
    | '/sitemap.xml'
    | '/solucoes'
    | '/termos-de-uso'
    | '/_authenticated/admin'
    | '/pagamento/aprovado'
    | '/pagamento/pendente'
    | '/pagamento/processando'
    | '/pagamento/recusado'
    | '/solucoes_/voz-protetora'
    | '/voz-protetora/$'
    | '/voz-protetora/'
    | '/api/public/keepalive'
    | '/_authenticated/app/'
    | '/_authenticated/app/voz-protetora/busca'
    | '/_authenticated/app/voz-protetora/como-usar'
    | '/_authenticated/app/voz-protetora/meu-passo'
    | '/_authenticated/app/voz-protetora/minha-assinatura'
    | '/_authenticated/app/voz-protetora/minha-presenca'
    | '/_authenticated/app/voz-protetora/minha-voz'
    | '/_authenticated/app/voz-protetora/notificacoes'
    | '/_authenticated/app/voz-protetora/preciso-de-ajuda'
    | '/api/public/webhooks/mercadopago'
    | '/_authenticated/app/voz-protetora/'
    | '/_authenticated/app/voz-protetora/aconteceu/$slug'
    | '/_authenticated/app/voz-protetora/bonus/$slug'
    | '/_authenticated/app/voz-protetora/fortalecer/$slug'
    | '/_authenticated/app/voz-protetora/vai-acontecer/$slug'
    | '/_authenticated/app/voz-protetora/aconteceu/'
    | '/_authenticated/app/voz-protetora/bonus/'
    | '/_authenticated/app/voz-protetora/fortalecer/'
    | '/_authenticated/app/voz-protetora/vai-acontecer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessibilidadeRoute: typeof AcessibilidadeRoute
  AcessoRoute: typeof AcessoRoute
  ApoieRoute: typeof ApoieRoute
  AuthRoute: typeof AuthRoute
  BussolaVozRoute: typeof BussolaVozRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  ConteudosRoute: typeof ConteudosRoute
  MetodologiaRoute: typeof MetodologiaRoute
  MeusProdutosRoute: typeof MeusProdutosRoute
  OMovimentoRoute: typeof OMovimentoRoute
  ParticipeRoute: typeof ParticipeRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RecursosRoute: typeof RecursosRoute
  SejaVozRoute: typeof SejaVozRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucoesRoute: typeof SolucoesRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  PagamentoAprovadoRoute: typeof PagamentoAprovadoRoute
  PagamentoPendenteRoute: typeof PagamentoPendenteRoute
  PagamentoProcessandoRoute: typeof PagamentoProcessandoRoute
  PagamentoRecusadoRoute: typeof PagamentoRecusadoRoute
  SolucoesVozProtetoraRoute: typeof SolucoesVozProtetoraRoute
  VozProtetoraSplatRoute: typeof VozProtetoraSplatRoute
  VozProtetoraIndexRoute: typeof VozProtetoraIndexRoute
  ApiPublicKeepaliveRoute: typeof ApiPublicKeepaliveRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessibilidade': {
      id: '/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/acessibilidade'
      preLoaderRoute: typeof AcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoie': {
      id: '/apoie'
      path: '/apoie'
      fullPath: '/apoie'
      preLoaderRoute: typeof ApoieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bussola-voz': {
      id: '/bussola-voz'
      path: '/bussola-voz'
      fullPath: '/bussola-voz'
      preLoaderRoute: typeof BussolaVozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-produtos': {
      id: '/meus-produtos'
      path: '/meus-produtos'
      fullPath: '/meus-produtos'
      preLoaderRoute: typeof MeusProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-movimento': {
      id: '/o-movimento'
      path: '/o-movimento'
      fullPath: '/o-movimento'
      preLoaderRoute: typeof OMovimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participe': {
      id: '/participe'
      path: '/participe'
      fullPath: '/participe'
      preLoaderRoute: typeof ParticipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-voz': {
      id: '/seja-voz'
      path: '/seja-voz'
      fullPath: '/seja-voz'
      preLoaderRoute: typeof SejaVozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pagamento/aprovado': {
      id: '/pagamento/aprovado'
      path: '/pagamento/aprovado'
      fullPath: '/pagamento/aprovado'
      preLoaderRoute: typeof PagamentoAprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/pendente': {
      id: '/pagamento/pendente'
      path: '/pagamento/pendente'
      fullPath: '/pagamento/pendente'
      preLoaderRoute: typeof PagamentoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/processando': {
      id: '/pagamento/processando'
      path: '/pagamento/processando'
      fullPath: '/pagamento/processando'
      preLoaderRoute: typeof PagamentoProcessandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/recusado': {
      id: '/pagamento/recusado'
      path: '/pagamento/recusado'
      fullPath: '/pagamento/recusado'
      preLoaderRoute: typeof PagamentoRecusadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes_/voz-protetora': {
      id: '/solucoes_/voz-protetora'
      path: '/solucoes/voz-protetora'
      fullPath: '/solucoes/voz-protetora'
      preLoaderRoute: typeof SolucoesVozProtetoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voz-protetora/': {
      id: '/voz-protetora/'
      path: '/voz-protetora'
      fullPath: '/voz-protetora/'
      preLoaderRoute: typeof VozProtetoraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voz-protetora/$': {
      id: '/voz-protetora/$'
      path: '/voz-protetora/$'
      fullPath: '/voz-protetora/$'
      preLoaderRoute: typeof VozProtetoraSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/keepalive': {
      id: '/api/public/keepalive'
      path: '/api/public/keepalive'
      fullPath: '/api/public/keepalive'
      preLoaderRoute: typeof ApiPublicKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/voz-protetora/': {
      id: '/_authenticated/app/voz-protetora/'
      path: '/app/voz-protetora'
      fullPath: '/app/voz-protetora/'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/busca': {
      id: '/_authenticated/app/voz-protetora/busca'
      path: '/app/voz-protetora/busca'
      fullPath: '/app/voz-protetora/busca'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/como-usar': {
      id: '/_authenticated/app/voz-protetora/como-usar'
      path: '/app/voz-protetora/como-usar'
      fullPath: '/app/voz-protetora/como-usar'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraComoUsarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/meu-passo': {
      id: '/_authenticated/app/voz-protetora/meu-passo'
      path: '/app/voz-protetora/meu-passo'
      fullPath: '/app/voz-protetora/meu-passo'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraMeuPassoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/minha-assinatura': {
      id: '/_authenticated/app/voz-protetora/minha-assinatura'
      path: '/app/voz-protetora/minha-assinatura'
      fullPath: '/app/voz-protetora/minha-assinatura'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraMinhaAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/minha-presenca': {
      id: '/_authenticated/app/voz-protetora/minha-presenca'
      path: '/app/voz-protetora/minha-presenca'
      fullPath: '/app/voz-protetora/minha-presenca'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraMinhaPresencaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/minha-voz': {
      id: '/_authenticated/app/voz-protetora/minha-voz'
      path: '/app/voz-protetora/minha-voz'
      fullPath: '/app/voz-protetora/minha-voz'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraMinhaVozRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/notificacoes': {
      id: '/_authenticated/app/voz-protetora/notificacoes'
      path: '/app/voz-protetora/notificacoes'
      fullPath: '/app/voz-protetora/notificacoes'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/preciso-de-ajuda': {
      id: '/_authenticated/app/voz-protetora/preciso-de-ajuda'
      path: '/app/voz-protetora/preciso-de-ajuda'
      fullPath: '/app/voz-protetora/preciso-de-ajuda'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraPrecisoDeAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/voz-protetora/aconteceu/': {
      id: '/_authenticated/app/voz-protetora/aconteceu/'
      path: '/app/voz-protetora/aconteceu'
      fullPath: '/app/voz-protetora/aconteceu/'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraAconteceuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/aconteceu/$slug': {
      id: '/_authenticated/app/voz-protetora/aconteceu/$slug'
      path: '/app/voz-protetora/aconteceu/$slug'
      fullPath: '/app/voz-protetora/aconteceu/$slug'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraAconteceuSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/bonus/': {
      id: '/_authenticated/app/voz-protetora/bonus/'
      path: '/app/voz-protetora/bonus'
      fullPath: '/app/voz-protetora/bonus/'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraBonusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/bonus/$slug': {
      id: '/_authenticated/app/voz-protetora/bonus/$slug'
      path: '/app/voz-protetora/bonus/$slug'
      fullPath: '/app/voz-protetora/bonus/$slug'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraBonusSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/fortalecer/': {
      id: '/_authenticated/app/voz-protetora/fortalecer/'
      path: '/app/voz-protetora/fortalecer'
      fullPath: '/app/voz-protetora/fortalecer/'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraFortalecerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/fortalecer/$slug': {
      id: '/_authenticated/app/voz-protetora/fortalecer/$slug'
      path: '/app/voz-protetora/fortalecer/$slug'
      fullPath: '/app/voz-protetora/fortalecer/$slug'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraFortalecerSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/vai-acontecer/': {
      id: '/_authenticated/app/voz-protetora/vai-acontecer/'
      path: '/app/voz-protetora/vai-acontecer'
      fullPath: '/app/voz-protetora/vai-acontecer/'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraVaiAcontecerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/voz-protetora/vai-acontecer/$slug': {
      id: '/_authenticated/app/voz-protetora/vai-acontecer/$slug'
      path: '/app/voz-protetora/vai-acontecer/$slug'
      fullPath: '/app/voz-protetora/vai-acontecer/$slug'
      preLoaderRoute: typeof AuthenticatedAppVozProtetoraVaiAcontecerSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppVozProtetoraBuscaRoute: typeof AuthenticatedAppVozProtetoraBuscaRoute
  AuthenticatedAppVozProtetoraComoUsarRoute: typeof AuthenticatedAppVozProtetoraComoUsarRoute
  AuthenticatedAppVozProtetoraMeuPassoRoute: typeof AuthenticatedAppVozProtetoraMeuPassoRoute
  AuthenticatedAppVozProtetoraMinhaAssinaturaRoute: typeof AuthenticatedAppVozProtetoraMinhaAssinaturaRoute
  AuthenticatedAppVozProtetoraMinhaPresencaRoute: typeof AuthenticatedAppVozProtetoraMinhaPresencaRoute
  AuthenticatedAppVozProtetoraMinhaVozRoute: typeof AuthenticatedAppVozProtetoraMinhaVozRoute
  AuthenticatedAppVozProtetoraNotificacoesRoute: typeof AuthenticatedAppVozProtetoraNotificacoesRoute
  AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute: typeof AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute
  AuthenticatedAppVozProtetoraIndexRoute: typeof AuthenticatedAppVozProtetoraIndexRoute
  AuthenticatedAppVozProtetoraAconteceuSlugRoute: typeof AuthenticatedAppVozProtetoraAconteceuSlugRoute
  AuthenticatedAppVozProtetoraBonusSlugRoute: typeof AuthenticatedAppVozProtetoraBonusSlugRoute
  AuthenticatedAppVozProtetoraFortalecerSlugRoute: typeof AuthenticatedAppVozProtetoraFortalecerSlugRoute
  AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute: typeof AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute
  AuthenticatedAppVozProtetoraAconteceuIndexRoute: typeof AuthenticatedAppVozProtetoraAconteceuIndexRoute
  AuthenticatedAppVozProtetoraBonusIndexRoute: typeof AuthenticatedAppVozProtetoraBonusIndexRoute
  AuthenticatedAppVozProtetoraFortalecerIndexRoute: typeof AuthenticatedAppVozProtetoraFortalecerIndexRoute
  AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute: typeof AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppVozProtetoraBuscaRoute:
    AuthenticatedAppVozProtetoraBuscaRoute,
  AuthenticatedAppVozProtetoraComoUsarRoute:
    AuthenticatedAppVozProtetoraComoUsarRoute,
  AuthenticatedAppVozProtetoraMeuPassoRoute:
    AuthenticatedAppVozProtetoraMeuPassoRoute,
  AuthenticatedAppVozProtetoraMinhaAssinaturaRoute:
    AuthenticatedAppVozProtetoraMinhaAssinaturaRoute,
  AuthenticatedAppVozProtetoraMinhaPresencaRoute:
    AuthenticatedAppVozProtetoraMinhaPresencaRoute,
  AuthenticatedAppVozProtetoraMinhaVozRoute:
    AuthenticatedAppVozProtetoraMinhaVozRoute,
  AuthenticatedAppVozProtetoraNotificacoesRoute:
    AuthenticatedAppVozProtetoraNotificacoesRoute,
  AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute:
    AuthenticatedAppVozProtetoraPrecisoDeAjudaRoute,
  AuthenticatedAppVozProtetoraIndexRoute:
    AuthenticatedAppVozProtetoraIndexRoute,
  AuthenticatedAppVozProtetoraAconteceuSlugRoute:
    AuthenticatedAppVozProtetoraAconteceuSlugRoute,
  AuthenticatedAppVozProtetoraBonusSlugRoute:
    AuthenticatedAppVozProtetoraBonusSlugRoute,
  AuthenticatedAppVozProtetoraFortalecerSlugRoute:
    AuthenticatedAppVozProtetoraFortalecerSlugRoute,
  AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute:
    AuthenticatedAppVozProtetoraVaiAcontecerSlugRoute,
  AuthenticatedAppVozProtetoraAconteceuIndexRoute:
    AuthenticatedAppVozProtetoraAconteceuIndexRoute,
  AuthenticatedAppVozProtetoraBonusIndexRoute:
    AuthenticatedAppVozProtetoraBonusIndexRoute,
  AuthenticatedAppVozProtetoraFortalecerIndexRoute:
    AuthenticatedAppVozProtetoraFortalecerIndexRoute,
  AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute:
    AuthenticatedAppVozProtetoraVaiAcontecerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessibilidadeRoute: AcessibilidadeRoute,
  AcessoRoute: AcessoRoute,
  ApoieRoute: ApoieRoute,
  AuthRoute: AuthRoute,
  BussolaVozRoute: BussolaVozRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  ConteudosRoute: ConteudosRoute,
  MetodologiaRoute: MetodologiaRoute,
  MeusProdutosRoute: MeusProdutosRoute,
  OMovimentoRoute: OMovimentoRoute,
  ParticipeRoute: ParticipeRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RecursosRoute: RecursosRoute,
  SejaVozRoute: SejaVozRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucoesRoute: SolucoesRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  PagamentoAprovadoRoute: PagamentoAprovadoRoute,
  PagamentoPendenteRoute: PagamentoPendenteRoute,
  PagamentoProcessandoRoute: PagamentoProcessandoRoute,
  PagamentoRecusadoRoute: PagamentoRecusadoRoute,
  SolucoesVozProtetoraRoute: SolucoesVozProtetoraRoute,
  VozProtetoraSplatRoute: VozProtetoraSplatRoute,
  VozProtetoraIndexRoute: VozProtetoraIndexRoute,
  ApiPublicKeepaliveRoute: ApiPublicKeepaliveRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
